In [6]:
# Load datasets (Iris & California Housing)
from sklearn.datasets import load_iris, fetch_california_housing
import pandas as pd

# Iris dataset (Classification)
iris = load_iris(as_frame=True)
X_iris, y_iris = iris.data, iris.target
iris_df = iris.frame

print("Iris Dataset:")
display(iris_df.head())

# California Housing dataset (Regression)
housing = fetch_california_housing(as_frame=True)
X_housing, y_housing = housing.data, housing.target
housing_df = housing.frame
housing_df['MedHouseVal'] = y_housing

print("California Housing Dataset:")
display(housing_df.head())

Iris Dataset:


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

California Housing Dataset:


MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  MedHouseVal  
0    -122.23        4.526  
1    -122.22        3.585  
2    -122.24        3.521  
3    -122.25        3.413  
4    -122.25        3.422

In [7]:
# Train-test split
from sklearn.model_selection import train_test_split

# Iris split
X_train_iris, X_test_iris, y_train_iris, y_test_iris = train_test_split(
    X_iris, y_iris, test_size=0.2, random_state=42)

# Housing split
X_train_housing, X_test_housing, y_train_housing, y_test_housing = train_test_split(
    X_housing, y_housing, test_size=0.2, random_state=42)

In [8]:
# Train models
from sklearn.linear_model import LogisticRegression, LinearRegression

# Logistic Regression (Iris)
iris_model = LogisticRegression(max_iter=200)
iris_model.fit(X_train_iris, y_train_iris)
iris_preds = iris_model.predict(X_test_iris)

# Linear Regression (Housing)
housing_model = LinearRegression()
housing_model.fit(X_train_housing, y_train_housing)
housing_preds = housing_model.predict(X_test_housing)

In [9]:
# Evaluation for Iris (Classification)
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

iris_acc = accuracy_score(y_test_iris, iris_preds)
iris_cm = confusion_matrix(y_test_iris, iris_preds)
iris_precision = precision_score(y_test_iris, iris_preds, average="macro")
iris_recall = recall_score(y_test_iris, iris_preds, average="macro")

print("Iris Model Evaluation")
print("Accuracy:", iris_acc)
print("Confusion Matrix:\n", iris_cm)
print("Precision:", iris_precision)
print("Recall:", iris_recall)

Iris Model Evaluation
Accuracy: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Precision: 1.0
Recall: 1.0


In [10]:
# Evaluation for Housing (Regression)
from sklearn.metrics import mean_squared_error
import numpy as np

housing_rmse = np.sqrt(mean_squared_error(y_test_housing, housing_preds))

print("Housing Model Evaluation")
print("RMSE:", housing_rmse)

Housing Model Evaluation
RMSE: 0.7455813830127764
